name: Artifacts
on: push
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - run: date > date.txt
            - uses: actions/upload-artifact@v4
              with:
                name: uploaded
                path: date.txt
                retention-days: 7
    download:
        runs-on: ubuntu-latest
        needs: [upload]
        steps:
            - uses: actions/download-artifact@v6
              with:
                name: uploaded
                path: downloaded
            - run: cat downloaded/date.txt